# Generated by Django 5.0.1 on 2024-04-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaughterhouseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, default='goats', max_length=255, null=True)),
                ('slaughter_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('confirm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('slaughtered', 'Slaughtered')], default='slaughtered', max_length=255)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('control_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.controlcenter')),
            ],
        ),
    ]
