# Generated by Django 5.0.1 on 2024-08-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0001_initial'),
        ('transaction', '0018_alter_breadertrade_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='breader_trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade'),
        ),
    ]
