# Generated by Django 5.0.1 on 2024-04-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0002_slaughterhouserecord_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterhouserecord',
            name='reference',
        ),
    ]
