# Generated by Django 5.0.1 on 2024-08-11 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0003_alter_slaughterhouserecord_breader_trade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breeder_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='last_confirmation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_confirmation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
