# Generated by Django 5.0.1 on 2024-04-18 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0006_slaughterhouserecord_last_confirmation_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='confirmed_by',
            field=models.ManyToManyField(related_name='confirmed_slaughterhouse_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
