# Generated by Django 5.0.1 on 2024-04-19 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0007_slaughterhouserecord_confirmed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterhouserecord',
            name='confirmed_by',
        ),
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_slaughterhouse_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
