# Generated by Django 5.0.1 on 2024-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0008_remove_slaughterhouserecord_confirmed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterhouserecord',
            name='confirm',
        ),
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='breed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='status',
            field=models.CharField(choices=[('deducted', 'Deducted')], default='slaughtered', max_length=255),
        ),
    ]
