# Generated by Django 5.0.1 on 2024-04-21 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0003_alter_customuser_address'),
        ('slaughter_house', '0009_remove_slaughterhouserecord_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
    ]
