# Generated by Django 5.0.1 on 2024-04-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0010_slaughterhouserecord_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
