# Generated by Django 5.0.1 on 2024-04-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcenter',
            name='net_breed_supply',
        ),
    ]
