# Generated by Django 5.0.1 on 2024-04-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_controlcenter_net_breed_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcenter',
            name='net_breed_supply',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
