# Generated by Django 5.0.1 on 2024-04-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_controlcenter_net_breed_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcenter',
            name='assigned_collateral_agent',
        ),
        migrations.AddField(
            model_name='controlcenter',
            name='assigned_collateral_agents',
            field=models.ManyToManyField(blank=True, related_name='assigned_control_centers', to='logistics.collateralmanager'),
        ),
    ]
