# Generated by Django 5.0.1 on 2024-04-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_controlcenter_assigned_collateral_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlcenter',
            old_name='assigned_collateral_agents',
            new_name='assigned_collateral_agent',
        ),
    ]
