# Generated by Django 5.0.1 on 2024-04-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_rename_assigned_collateral_agents_controlcenter_assigned_collateral_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcenter',
            name='assigned_collateral_agent',
        ),
        migrations.AddField(
            model_name='controlcenter',
            name='assigned_collateral_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.collateralmanager'),
        ),
    ]
