# Generated by Django 5.0.1 on 2024-08-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0007_remove_letterofcredit_dispute_resolution_and_more'),
        ('logistics', '0005_logisticsstatus_part_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcenter',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.buyer'),
        ),
    ]
