# Generated by Django 5.0.1 on 2024-04-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0011_alter_letterofcredit_text_content'),
        ('logistics', '0006_remove_controlcenter_assigned_collateral_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsstatus',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.invoice'),
        ),
    ]
