# Generated by Django 5.0.1 on 2024-04-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_logisticsstatus_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsstatus',
            name='bill_of_lading',
            field=models.FileField(blank=True, null=True, upload_to='bill_of_landings'),
        ),
    ]
