# Generated by Django 5.0.1 on 2024-03-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_alter_logisticsstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsstatus',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('arrived', 'Arrival'), ('received', 'Received')], default='Dispatched', max_length=255),
        ),
    ]
