# Generated by Django 5.0.1 on 2024-03-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_alter_logisticsstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateralmanager',
            name='associated_seller',
        ),
    ]
