# Generated by Django 5.0.1 on 2024-04-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_controlcenter_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcenter',
            name='users',
        ),
    ]
