# Generated by Django 5.0.1 on 2024-08-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_controlcenter_assigned_collateral_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcenter',
            name='total_slaughtered',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='controlcenter',
            name='total_supplied',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='controlcenter',
            name='total_weight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
