# Generated by Django 5.0.1 on 2024-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_controlcenter_total_slaughtered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprogress',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
