# Generated by Django 5.0.1 on 2024-08-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_packageinfo_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsstatus',
            name='part_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logisticsstatus',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logisticsstatus',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='logisticsstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Dispatched', max_length=255),
        ),
    ]
