# Generated by Django 5.0.1 on 2024-05-10 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_registration', '0002_initial'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, default='goats', max_length=255, null=True)),
                ('status', models.CharField(choices=[('in_the warehouse', 'In The Warehouse'), ('slaughtered', 'Slaughtered'), ('sold', 'Sold')], default='in_yard', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BreedCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity_left', models.PositiveIntegerField(default=0, editable=False)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBreedSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_type', models.CharField(choices=[('export', 'Export'), ('local_sale_cut', 'Local Sale Cut')], max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller')),
            ],
        ),
    ]
