# Generated by Django 5.0.1 on 2024-04-21 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0003_alter_customuser_address'),
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybreedsales',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='inventorybreedsales',
            name='status',
        ),
        migrations.RemoveField(
            model_name='inventorybreedsales',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='inventorybreedsales',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
        migrations.AlterField(
            model_name='inventorybreedsales',
            name='breed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventorybreedsales',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
