# Generated by Django 5.0.1 on 2024-04-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_remove_inventorybreedsales_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreedsales',
            name='sale_type',
            field=models.CharField(choices=[('export', 'Export'), ('local_sale_cut', 'Local Sale Cut')], max_length=255),
        ),
    ]
