# Generated by Django 5.0.1 on 2024-04-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_alter_inventorybreedsales_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybreedsales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
