# Generated by Django 5.0.1 on 2024-04-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_alter_inventorybreedsales_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybreedsales',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
