# Generated by Django 5.0.1 on 2024-07-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_breadertrade_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breadertrade',
            old_name='goat_weight',
            new_name='weight',
        ),
    ]
