# Generated by Django 5.0.1 on 2024-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_breadertrade_dead_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
