# Generated by Django 5.0.1 on 2024-08-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_breadertrade_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breadertrade',
            old_name='dead_condition',
            new_name='destroyed_condition',
        ),
    ]
