# Generated by Django 5.0.1 on 2024-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_rename_dead_condition_breadertrade_destroyed_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='destroyed_condition',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breadertrade',
            name='good_condition',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breadertrade',
            name='poor_condition',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breadertrade',
            name='received_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
