# Generated by Django 5.0.1 on 2024-08-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_breadertrade_requested_quanity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='reference',
            field=models.CharField(max_length=20),
        ),
    ]
