# Generated by Django 5.0.1 on 2024-08-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_alter_breadertrade_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='record_created',
            field=models.BooleanField(default=False),
        ),
    ]
