# Generated by Django 5.0.1 on 2024-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0020_breadertrade_temp_breeds_supplied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
