# Generated by Django 5.0.1 on 2024-03-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0028_remove_breader_seller_breadertrade_control_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadertrade',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='breadertrade',
            name='email',
        ),
        migrations.RemoveField(
            model_name='breadertrade',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='breadertrade',
            name='phone_number',
        ),
    ]
