# Generated by Django 5.0.1 on 2024-07-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0006_letterofcredit_collection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofcredit',
            name='dispute_resolution',
        ),
        migrations.RemoveField(
            model_name='letterofcredit',
            name='governing_law',
        ),
        migrations.RemoveField(
            model_name='letterofcredit',
            name='inspection_terms',
        ),
        migrations.RemoveField(
            model_name='letterofcredit',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='letterofcredit',
            name='packing_marking',
        ),
        migrations.RemoveField(
            model_name='letterofcredit',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='letterofcredit',
            name='text_content',
        ),
    ]
