# Generated by Django 5.0.1 on 2024-05-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
