# Generated by Django 5.0.1 on 2024-07-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_breader_created_at_alter_breadertrade_breeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
