# Generated by Django 5.0.1 on 2024-07-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0007_remove_letterofcredit_dispute_resolution_and_more'),
        ('transaction', '0005_rename_goat_weight_breadertrade_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='letter_of_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.letterofcredit'),
        ),
    ]
