# Generated by Django 5.0.1 on 2024-08-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_breadertrade_breeder'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='dead_condition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='good_condition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='poor_condition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='received_weight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='reception_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
