# Generated by Django 5.0.1 on 2024-08-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_alter_breadertrade_destroyed_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
