# Generated by Django 5.0.1 on 2024-08-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_breadertrade_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='part_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='part_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('export', 'Export'), ('local_sale_cut', 'Local Sale Cut')], max_length=255, null=True),
        ),
    ]
