# Generated by Django 5.0.1 on 2024-08-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_breadertrade_part_name_breadertrade_part_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
