# Generated by Django 5.0.1 on 2024-08-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_breadertrade_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='first_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_confirmed_slaughterhouse_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='last_confirmation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_confirmed_slaughterhouse_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
