# Generated by Django 5.0.1 on 2024-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_breadertrade_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='requested_quanity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
