# Generated by Django 5.0.1 on 2024-08-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_breadertrade_record_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='temp_breeds_supplied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='temp_weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
