# Generated by Django 5.0.1 on 2024-08-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0021_breadertrade_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadertrade',
            name='status',
        ),
    ]
