# Generated by Django 5.0.1 on 2024-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0022_remove_breadertrade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='initial_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='slauhtered_weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
