# Generated by Django 5.0.1 on 2024-04-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
