# Generated by Django 5.0.1 on 2024-07-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='item',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
