# Generated by Django 5.0.1 on 2024-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0002_letterofcredit_created_on_letterofcredit_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letterofcredit',
            old_name='date',
            new_name='delivery_date',
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
