# Generated by Django 5.0.1 on 2024-04-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0002_quotation_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
