# Generated by Django 5.0.1 on 2024-04-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0003_quotation_reject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='reject',
            new_name='rejected',
        ),
    ]
