# Generated by Django 5.0.1 on 2024-07-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0003_rename_date_letterofcredit_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofcredit',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='letterofcredit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='dispute_resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='governing_law',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='inspection_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='insurance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='packing_marking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='item',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
