# Generated by Django 5.0.1 on 2024-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0004_remove_letterofcredit_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
