# Generated by Django 5.0.1 on 2024-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0005_letterofcredit_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
