# Generated by Django 5.0.1 on 2024-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0006_alter_letterofcredit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofcredit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_to_bank', 'Sent to bank'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='sent_to_bank', max_length=255),
        ),
    ]
