# Generated by Django 5.0.1 on 2025-01-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0007_remove_letterofcredit_dispute_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofcredit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_to_seller', 'Sent to Seller'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='sent_to_seller', max_length=255),
        ),
    ]
