# Generated by Django 5.0.1 on 2024-04-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0007_alter_letterofcredit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofcredit',
            name='rejection_reason',
        ),
    ]
