# Generated by Django 5.0.1 on 2025-01-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0008_alter_letterofcredit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='buyer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_to_bank', 'Sent to bank'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='sent_to_bank', max_length=255),
        ),
    ]
