# Generated by Django 5.0.1 on 2024-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0008_remove_letterofcredit_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
