# Generated by Django 5.0.1 on 2024-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0009_letterofcredit_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='text_content',
            field=models.TextField(blank=True),
        ),
    ]
