# Generated by Django 5.0.1 on 2025-01-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0009_letterofcredit_buyer_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofcredit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_to_seller', 'Sent to seller'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='sent_to_bank', max_length=255),
        ),
    ]
