# Generated by Django 5.0.1 on 2024-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0010_letterofcredit_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofcredit',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
