# Generated by Django 5.0.1 on 2024-04-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0011_alter_letterofcredit_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='collection_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
