# Generated by Django 5.0.1 on 2025-01-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0011_alter_letterofcredit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofcredit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_to_seller', 'Sent to seller'), ('approved', 'Approved'), ('buyer_approval', 'Buyer Approved'), ('buyer_rejected', 'Buyer Rejected'), ('rejected', 'Rejected')], default='sent_to_bank', max_length=255),
        ),
    ]
