# Generated by Django 5.0.1 on 2025-01-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0012_alter_letterofcredit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='buyer_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
