# Generated by Django 5.0.1 on 2024-04-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0012_letterofcredit_collection_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
