# Generated by Django 5.0.1 on 2024-03-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0049_quotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofcredit',
            name='quotation',
        ),
    ]
