# Generated by Django 5.0.1 on 2024-03-16 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0050_remove_letterofcredit_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='quotatation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.quotation'),
        ),
    ]
