# Generated by Django 5.0.1 on 2024-03-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
