# Generated by Django 5.0.1 on 2024-04-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0012_alter_customuser_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('no_role', 'No Role'), ('abattoir', 'Abattoir'), ('bank', 'Bank'), ('employee', 'employee'), ('superuser', 'Superuser'), ('breeder', 'Breeder'), ('regular', 'regular'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('warehouse_personnel', 'Warehouse Personnel'), ('inventory_manager', 'Inventory Manager'), ('admin', 'Admin'), ('slaughterhouse_manager', 'Slaughterhouse Manager'), ('collateral_manager', 'Collateral Manager')], default='no_role', max_length=255),
        ),
    ]
