# Generated by Django 5.0.1 on 2024-04-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0014_customuser_bank_customuser_bank_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bank',
            new_name='bank_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
