# Generated by Django 5.0.1 on 2024-04-01 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0015_rename_bank_customuser_bank_name_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank_abbreviation',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='swift_code',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='bank_branch_id',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='head_office',
        ),
        migrations.AddField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.bank'),
        ),
    ]
